"""Add tenant owner

Revision ID: 5d39b5ba2882
Revises: a74a8f05366b
Create Date: 2026-09-19 17:10:04.032983+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5d39b5ba2882'
down_revision: str | None = 'a74a8f05366b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('user_owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tenants', 'users', ['user_owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'user_owner_id')
    # ### end Alembic commands ###
